add solution for 01-checkbox
js-tasks-ru/htmlcss-20211125_x100best pull request #14
Opened 2021-12-21 12:34 UTC by x100best

2021-12-21 12:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-22 15:38 UTC, GSemikozov requested changes

2021-12-22 15:38 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +	margin-bottom: 15px;
ой, марджины на уровне блока не задаем

2021-12-22 15:38 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +	background: var(--grey-2);
если надо просто скрыть иконку, то нам ничего не мешает использовать display: none))

2022-01-05 22:03 UTC, GSemikozov approved these changes

2022-01-05 22:03 UTC, merged