draft-solution for 03-toggler
js-tasks-ru/htmlcss-20211125_x100best pull request #16
Opened 2022-01-04 13:27 UTC by x100best

2022-01-04 13:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-06 12:21 UTC, GSemikozov requested changes

2022-01-06 12:21 UTC, GSemikozov commented on 07-lection5/03-toggler/toggler.css
> +	margin-left: 12px;
точно работает как надо, внутри .toggler__state?)

2022-01-06 12:32 UTC, x100best commented on 07-lection5/03-toggler/toggler.css
> +	margin-left: 12px;
Ну стили эти все работают

2022-01-06 18:01 UTC, GSemikozov approved these changes

2022-01-06 18:02 UTC, merged