Lection1 01 button
js-tasks-ru/htmlcss-20211125_x100best pull request #3
Opened 2021-12-06 12:42 UTC by x100best

1st task - lection1

2021-12-06 12:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-06 13:04 UTC, GSemikozov requested changes

2021-12-06 13:04 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +/* Reset */
все сбросы вплоть до 72 строки надо унести в соответствующий файл. В файле компонента могут быть стили только этого компонента

2021-12-06 13:04 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button__primary,
модификаторы пишем через 1 нижнее подчеркивание + вместо .button__primary-disabled лучше использовать общий для всех типов кнопок модификатор .button_disabled

2021-12-06 13:04 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	color: #ffffff;
тут и ниже - все цвета вставляем как переменные; если их еще нет в переменных - создаем

2021-12-06 13:04 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +	opacity: 0.5;
еще чтобы пользователь не мог взаимодействовать с такими элементами добавляем pointer-events: none

2021-12-06 15:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-07 16:33 UTC, GSemikozov requested changes

2021-12-07 16:33 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import "./reset.css";
зачем?)

2021-12-07 16:33 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import "../../assets/css/main.css";
зачем?)

2021-12-07 16:33 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import "../../assets/css/main.css";
эти файлы мы подключаем 1 раз, причем - глобально, а значит не нужно их импортировать еще и отдельно в каждый компонент

2021-12-07 16:33 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.primary {
у primary + secondary + alternate дублируются свойства, а ко всему прочему они дублируются еще и для соответствующих модификаторов - этот ошибка

2021-12-07 16:33 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.primary {
правильно делать так:

1. для блока .button определяем все общие для всех типов кнопок стили
2. затем добавляем модификаторы типов и добавляем только то, что специфическим образом модифицирует кнопку (например, фон - `.button_primary { background-color: color; }`)

2021-12-07 16:33 UTC, GSemikozov commented on 03-lection1/01-button/reset.css
> +/* Reset */
этот файл - это общие - глобальные - сбросы, поэтому его надо унести в assets/css/ и подключать оттуда в главный шаблон страницы или в main.css

2021-12-07 16:33 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.primary {
блок .primary? нет, блок у нас - это .button, у которого могут быть разные модификаторы, например .button_primary

2021-12-08 14:19 UTC, GSemikozov approved these changes

2021-12-08 14:19 UTC, merged