Accordion
js-tasks-ru/htmlcss-20211125_x100best pull request #4
Opened 2021-12-07 11:49 UTC by x100best

2021-12-07 11:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-08 14:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-08 15:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-08 20:45 UTC, GSemikozov requested changes

2021-12-08 20:45 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.container {
если этот стиль вспомогательный и нигде не будет переиспользоваться кроме страницы с решением задачи - тогда надо унести в тег style хтмл страницы

2021-12-08 20:45 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	width: 730px;
на мобилке будут проблемы)
лучше max-width

2021-12-08 20:45 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +	margin: -8px 49px 24px 32px;
тут все-таки паддинги и желательно не использовать отрицательное значение

2021-12-09 11:08 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-09 11:17 UTC, GSemikozov requested changes

2021-12-09 11:17 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion__summary {
у summary и у text не хватает стилей для описания текста)

2021-12-09 11:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-09 12:06 UTC, GSemikozov approved these changes

2021-12-09 12:06 UTC, merged